#!/usr/bin/env bash

## Hastebin Bash Client
## Modified from bash ver in https://github.com/seejohnrun/haste-client

if [ -z "$HASTE_SERVER" ] ; then
  echo Please set HASTE_SERVER >&2
  exit 1
fi

# Input is $1, fallback to stdin
# If HASTE_BASE64_ENC is set,
input="${1:-/dev/stdin}"

if [ -n "$HASTE_BASE64_ENC" ] ; then
    cmd=base64
else
    cmd=cat
fi

curl -X POST -s --data-binary @<($cmd "${input}") "$HASTE_SERVER/documents" | \
  awk -F '"' '{print ENVIRON["HASTE_SERVER"] "/raw/" $4}'